name: Build and Deploy Documentation

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Saca el código
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0   # necesario para gh-pages

      # 2. Prepara Python
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3. Instala Jupyter Book y tema
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter-book sphinx-book-theme

      # 4. Construye el sitio
      - name: Build Jupyter Book
        run: jupyter-book build documentation/

      # 5. Despliega a la rama gh-pages
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: documentation/_build/html
